[project]
name = "src"
version = "0.0.1"
description = "Agentic RAG project"
authors = [{name = "your name", email = "youremail@gmail.com"}]

[tool.setuptools]
packages = {find = {}}

[tool.setuptools.dynamic]
dependencies = {file = "requirements.txt"}